"use client";

import { useState, useEffect } from "react";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import EmptyState from "@/components/ui/EmptyState";
import LoadingState from "@/components/ui/LoadingState";

type RoadmapTask = {
  id: string;
  title: string;
  status: string;
  priority: string;
  dueDay: number | null;
  assignedTo: { id: string; name: string } | null;
};

type RoadmapModule = {
  id: string;
  title: string;
  description: string | null;
  tasks: RoadmapTask[];
};

type RoadmapMonth = {
  id: string;
  monthNumber: number;
  title: string;
  modules: RoadmapModule[];
};

type Roadmap = {
  id: string;
  title: string;
  months: RoadmapMonth[];
};

export default function ClientRoadmapPage() {
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null);
  const [activeMonth, setActiveMonth] = useState(0);
  const [expandedModules, setExpandedModules] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchRoadmap() {
      try {
        const res = await fetch("/api/roadmap/my");
        const data = await res.json();
        setRoadmap(data);
        if (data?.months?.length > 0) {
          const allModuleIds = data.months.flatMap((m: RoadmapMonth) =>
            m.modules.map((mod: RoadmapModule) => mod.id)
          );
          setExpandedModules(new Set(allModuleIds));
        }
      } catch {
        setRoadmap(null);
      } finally {
        setLoading(false);
      }
    }
    fetchRoadmap();
  }, []);

  function toggleModule(moduleId: string) {
    setExpandedModules((prev) => {
      const next = new Set(prev);
      if (next.has(moduleId)) next.delete(moduleId);
      else next.add(moduleId);
      return next;
    });
  }

  function getModuleStats(tasks: RoadmapTask[]) {
    const total = tasks.length;
    const completed = tasks.filter((t) => t.status === "COMPLETED").length;
    const percent = total > 0 ? Math.round((completed / total) * 100) : 0;
    return { total, completed, percent };
  }

  function getOverallStats() {
    if (!roadmap) return { total: 0, completed: 0, inProgress: 0, percent: 0 };
    const allTasks = roadmap.months.flatMap((m) =>
      m.modules.flatMap((mod) => mod.tasks)
    );
    const total = allTasks.length;
    const completed = allTasks.filter((t) => t.status === "COMPLETED").length;
    const inProgress = allTasks.filter((t) => t.status === "IN_PROGRESS").length;
    const percent = total > 0 ? Math.round((completed / total) * 100) : 0;
    return { total, completed, inProgress, percent };
  }

  const overall = getOverallStats();

  return (
    <div className="space-y-8 max-w-5xl">
      <div>
        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">My 90-Day SEO Roadmap</h1>
        <p className="text-sm text-slate-500 mt-1">
          Follow your website search optimization journey step by step.
        </p>
      </div>

      {loading ? (
        <Card padding="none">
          <LoadingState message="Loading your roadmap..." />
        </Card>
      ) : !roadmap ? (
        <EmptyState
          icon="🗺️"
          title="No roadmap assigned yet"
          description="Your dedicated 90-day SEO strategy roadmap will appear here once generated by our strategy team."
        />
      ) : (
        <div className="space-y-6">
          {/* Progress Card */}
          <Card>
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-base font-bold text-slate-900">Overall Execution Progress</h2>
              <span className="text-2xl font-black text-emerald-600">{overall.percent}%</span>
            </div>
            <div className="w-full bg-slate-100 rounded-full h-3 mb-3">
              <div
                className="bg-emerald-500 h-3 rounded-full transition-all duration-300"
                style={{ width: `${overall.percent}%` }}
              />
            </div>
            <div className="flex gap-6 text-xs font-semibold text-slate-500">
              <span>✅ {overall.completed} completed</span>
              <span>⏳ {overall.inProgress} in progress</span>
              <span>📋 {overall.total} total roadmap milestones</span>
            </div>
          </Card>

          {/* Month Tabs */}
          <div className="flex gap-2">
            {roadmap.months.map((month, index) => (
              <button
                key={month.id}
                onClick={() => setActiveMonth(index)}
                className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                  activeMonth === index
                    ? "bg-slate-900 text-white shadow-xs"
                    : "bg-white text-slate-600 border border-slate-200 hover:bg-slate-50"
                }`}
              >
                Month {month.monthNumber}
              </button>
            ))}
          </div>

          {/* Active Month */}
          {roadmap.months[activeMonth] && (
            <div className="space-y-4">
              <h3 className="text-base font-bold text-slate-900">
                {roadmap.months[activeMonth].title}
              </h3>

              <div className="flex flex-col gap-4">
                {roadmap.months[activeMonth].modules.map((mod) => {
                  const stats = getModuleStats(mod.tasks);
                  const isExpanded = expandedModules.has(mod.id);

                  return (
                    <Card key={mod.id} padding="none" className="overflow-hidden">
                      <button
                        onClick={() => toggleModule(mod.id)}
                        className="w-full flex items-center justify-between p-5 hover:bg-slate-50/60 transition-colors text-left cursor-pointer"
                      >
                        <div className="flex items-center gap-3">
                          <span className="text-xs text-slate-400">{isExpanded ? "▼" : "▶"}</span>
                          <div>
                            <h4 className="text-sm font-bold text-slate-900">{mod.title}</h4>
                            {mod.description && (
                              <p className="text-xs text-slate-500 mt-0.5">{mod.description}</p>
                            )}
                          </div>
                        </div>
                        <div className="text-right ml-4">
                          <p className="text-xs font-semibold text-slate-500">
                            {stats.completed}/{stats.total} done
                          </p>
                          <div className="w-20 bg-slate-100 rounded-full h-1.5 mt-1">
                            <div
                              className="bg-emerald-500 h-1.5 rounded-full"
                              style={{ width: `${stats.percent}%` }}
                            />
                          </div>
                        </div>
                      </button>

                      {isExpanded && (
                        <div className="border-t border-slate-100 divide-y divide-slate-100 bg-slate-50/30">
                          {mod.tasks.map((task) => (
                            <div key={task.id} className="p-4 flex items-center gap-3 flex-wrap">
                              <span className="text-base">
                                {task.status === "COMPLETED" ? "✅" :
                                 task.status === "IN_PROGRESS" ? "⏳" :
                                 task.status === "BLOCKED" ? "🚫" : "⬜"}
                              </span>

                              <div className="flex-1 min-w-48">
                                <p className={`text-sm font-semibold ${
                                  task.status === "COMPLETED" ? "line-through text-slate-400" : "text-slate-900"
                                }`}>
                                  {task.title}
                                </p>
                                {task.dueDay && (
                                  <p className="text-[11px] text-slate-400 mt-0.5">Target: Day {task.dueDay}</p>
                                )}
                              </div>

                              <Badge type="priority" value={task.priority} />
                              <Badge type="status" value={task.status} />

                              {task.assignedTo && (
                                <span className="text-xs text-slate-500 font-medium">
                                  👤 {task.assignedTo.name}
                                </span>
                              )}
                            </div>
                          ))}
                        </div>
                      )}
                    </Card>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}