"use client";

import { useState, useEffect } from "react";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import EmptyState from "@/components/ui/EmptyState";
import LoadingState from "@/components/ui/LoadingState";

type RoadmapTask = {
  id: string;
  title: string;
  status: string;
  priority: string;
  dueDay: number | null;
  assignedTo: { id: string; name: string } | null;
};

type RoadmapModule = {
  id: string;
  title: string;
  description: string | null;
  tasks: RoadmapTask[];
};

type RoadmapMonth = {
  id: string;
  monthNumber: number;
  title: string;
  modules: RoadmapModule[];
};

type Roadmap = {
  id: string;
  title: string;
  client: { id: string; name: string; email: string };
  months: RoadmapMonth[];
};

export default function EmployeeRoadmapsPage() {
  const [roadmaps, setRoadmaps] = useState<Roadmap[]>([]);
  const [activeRoadmap, setActiveRoadmap] = useState(0);
  const [activeMonth, setActiveMonth] = useState(0);
  const [expandedModules, setExpandedModules] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchRoadmaps() {
      try {
        const res = await fetch("/api/roadmap/employee");
        const data = await res.json();
        const list = Array.isArray(data) ? data : [];
        setRoadmaps(list);

        if (list.length > 0) {
          const allModuleIds = list[0].months.flatMap((m: RoadmapMonth) =>
            m.modules.map((mod: RoadmapModule) => mod.id)
          );
          setExpandedModules(new Set(allModuleIds));
        }
      } catch {
        setRoadmaps([]);
      } finally {
        setLoading(false);
      }
    }
    fetchRoadmaps();
  }, []);

  function toggleModule(moduleId: string) {
    setExpandedModules((prev) => {
      const next = new Set(prev);
      if (next.has(moduleId)) next.delete(moduleId);
      else next.add(moduleId);
      return next;
    });
  }

  function switchRoadmap(index: number) {
    setActiveRoadmap(index);
    setActiveMonth(0);
    if (roadmaps[index]) {
      const allModuleIds = roadmaps[index].months.flatMap((m) =>
        m.modules.map((mod) => mod.id)
      );
      setExpandedModules(new Set(allModuleIds));
    }
  }

  function getModuleStats(tasks: RoadmapTask[]) {
    const total = tasks.length;
    const completed = tasks.filter((t) => t.status === "COMPLETED").length;
    const percent = total > 0 ? Math.round((completed / total) * 100) : 0;
    return { total, completed, percent };
  }

  function getOverallStats(roadmap: Roadmap) {
    const allTasks = roadmap.months.flatMap((m) =>
      m.modules.flatMap((mod) => mod.tasks)
    );
    const total = allTasks.length;
    const completed = allTasks.filter((t) => t.status === "COMPLETED").length;
    const percent = total > 0 ? Math.round((completed / total) * 100) : 0;
    return { total, completed, percent };
  }

  const currentRoadmap = roadmaps[activeRoadmap];

  return (
    <div className="space-y-8 max-w-6xl">
      <div>
        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Client Roadmaps</h1>
        <p className="text-sm text-slate-500 mt-1">Review 90-day SEO execution plans for agency clients.</p>
      </div>

      {loading ? (
        <Card padding="none">
          <LoadingState message="Loading client roadmaps..." />
        </Card>
      ) : roadmaps.length === 0 ? (
        <EmptyState
          icon="🗺️"
          title="No active roadmaps found"
          description="Client roadmaps will appear here once generated by the admin team."
        />
      ) : (
        <div className="space-y-6">
          {/* Client Tabs */}
          {roadmaps.length > 1 && (
            <div className="flex gap-2 flex-wrap border-b border-slate-200 pb-3">
              {roadmaps.map((roadmap, index) => (
                <button
                  key={roadmap.id}
                  onClick={() => switchRoadmap(index)}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                    activeRoadmap === index
                      ? "bg-indigo-600 text-white shadow-xs"
                      : "bg-white text-slate-600 border border-slate-200 hover:bg-slate-50"
                  }`}
                >
                  🤝 {roadmap.client.name}
                </button>
              ))}
            </div>
          )}

          {currentRoadmap && (
            <>
              {/* Overall Progress Banner */}
              <Card>
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <h2 className="text-lg font-bold text-slate-900">{currentRoadmap.client.name}</h2>
                    <p className="text-xs text-slate-400">{currentRoadmap.client.email}</p>
                  </div>
                  <span className="text-2xl font-black text-indigo-600">
                    {getOverallStats(currentRoadmap).percent}%
                  </span>
                </div>
                <div className="w-full bg-slate-100 rounded-full h-2.5 mb-2">
                  <div
                    className="bg-indigo-600 h-2.5 rounded-full transition-all duration-300"
                    style={{ width: `${getOverallStats(currentRoadmap).percent}%` }}
                  />
                </div>
                <div className="flex gap-4 text-xs font-medium text-slate-500">
                  <span>✅ {getOverallStats(currentRoadmap).completed} completed</span>
                  <span>📋 {getOverallStats(currentRoadmap).total} total tasks</span>
                </div>
              </Card>

              {/* Month Tabs */}
              <div className="flex gap-2">
                {currentRoadmap.months.map((month, index) => (
                  <button
                    key={month.id}
                    onClick={() => setActiveMonth(index)}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                      activeMonth === index
                        ? "bg-slate-900 text-white"
                        : "bg-white text-slate-600 border border-slate-200 hover:bg-slate-50"
                    }`}
                  >
                    Month {month.monthNumber}
                  </button>
                ))}
              </div>

              {/* Active Month Content */}
              {currentRoadmap.months[activeMonth] && (
                <div className="space-y-4">
                  <h3 className="text-base font-bold text-slate-900">
                    {currentRoadmap.months[activeMonth].title}
                  </h3>

                  <div className="flex flex-col gap-4">
                    {currentRoadmap.months[activeMonth].modules.map((mod) => {
                      const stats = getModuleStats(mod.tasks);
                      const isExpanded = expandedModules.has(mod.id);

                      return (
                        <Card key={mod.id} padding="none" className="overflow-hidden">
                          <button
                            onClick={() => toggleModule(mod.id)}
                            className="w-full flex items-center justify-between p-5 hover:bg-slate-50/60 transition-colors text-left cursor-pointer"
                          >
                            <div className="flex items-center gap-3">
                              <span className="text-xs text-slate-400">{isExpanded ? "▼" : "▶"}</span>
                              <div>
                                <h4 className="text-sm font-bold text-slate-900">{mod.title}</h4>
                                {mod.description && (
                                  <p className="text-xs text-slate-500 mt-0.5">{mod.description}</p>
                                )}
                              </div>
                            </div>
                            <div className="text-right ml-4">
                              <p className="text-xs font-semibold text-slate-500">
                                {stats.completed}/{stats.total} done
                              </p>
                              <div className="w-20 bg-slate-100 rounded-full h-1.5 mt-1">
                                <div
                                  className="bg-indigo-600 h-1.5 rounded-full"
                                  style={{ width: `${stats.percent}%` }}
                                />
                              </div>
                            </div>
                          </button>

                          {isExpanded && (
                            <div className="border-t border-slate-100 divide-y divide-slate-100 bg-slate-50/30">
                              {mod.tasks.map((task) => (
                                <div key={task.id} className="p-4 flex items-center gap-3 flex-wrap">
                                  <span className="text-base">
                                    {task.status === "COMPLETED" ? "✅" :
                                     task.status === "IN_PROGRESS" ? "⏳" :
                                     task.status === "BLOCKED" ? "🚫" : "⬜"}
                                  </span>

                                  <div className="flex-1 min-w-48">
                                    <p className={`text-sm font-semibold ${
                                      task.status === "COMPLETED" ? "line-through text-slate-400" : "text-slate-900"
                                    }`}>
                                      {task.title}
                                    </p>
                                    {task.dueDay && (
                                      <p className="text-[11px] text-slate-400 mt-0.5">Day {task.dueDay}</p>
                                    )}
                                  </div>

                                  <Badge type="priority" value={task.priority} />
                                  <Badge type="status" value={task.status} />

                                  {task.assignedTo && (
                                    <span className="text-xs text-slate-500 font-medium">
                                      👤 {task.assignedTo.name}
                                    </span>
                                  )}
                                </div>
                              ))}
                            </div>
                          )}
                        </Card>
                      );
                    })}
                  </div>
                </div>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}